name: edunudge
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  geolocator: ^12.0.0
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.12
  image_picker: ^1.0.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  pdf: ^3.11.3
  printing: ^5.14.2
  google_maps_flutter: ^2.2.3
  pie_chart: ^5.1.0
  fl_chart: ^0.65.0
  table_calendar: ^3.0.9
  flutter_screenutil: ^5.9.0
  path_provider: ^2.0.15
  open_file: ^3.2.1
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1

  # âœ… Firebase Dependencies
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  firebase_messaging: ^15.2.10
  cloud_firestore: ^5.0.0

  http: ^1.2.0
  cupertino_icons: ^1.0.6
  permission_handler: ^11.0.0
  location: ^5.0.3
  flutter_dotenv: ^6.0.0
  workmanager: ^0.9.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - images/logo_notname.png
    - assets/.env
  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Regular.ttf
        - asset: assets/fonts/Kanit-Bold.ttf
          weight: 700

